spring.application.name=document-ai

# Vertex AI Gemini Configuration
spring.ai.vertex.ai.gemini.project-id=documentai-493805
spring.ai.vertex.ai.gemini.location=us-central1

# Vertex AI Embedding Configuration
spring.ai.vertex.ai.embedding.project-id=documentai-493805
spring.ai.vertex.ai.embedding.location=us-central1
spring.ai.vertex.ai.embedding.options.model=text-embedding-004
# Root path for credentials (assumed to be in the main DocumentAI folder)
spring.cloud.gcp.credentials.location=file:/home/dilshan/Desktop/Projects/DocumentAI/Documentai-API-Key.json

# ChromaDB Vector Store Configuration
spring.ai.vectorstore.chroma.client.host=http://localhost
spring.ai.vectorstore.chroma.client.port=8000
spring.ai.vectorstore.chroma.initialize-schema=false
spring.ai.vectorstore.chroma.collection-name=enterprise_pdfs

# Firebase Configuration (Custom properties for our FirebaseConfig class)
firebase.config.path=file:/home/dilshan/Desktop/Projects/DocumentAI/firebase-service-account.json

# Server port (optional)
server.port=8081
